### ISSUE TITLE
Details of SNSCT Mozilla Campus Club

### ISSUE THREAD

**Issue by surentharan** [Collaborate-Clubs/CCC-Main#1]
###Club name : **SNSCT Mozilla Campus Club**

###Club captain name : **Surentharan**

###Club city : **Coimbatore**

###Club email/Captain email address : **surentharan14@gmail.com**

###Status of the club on campus club website : **Active**

###Are you aware of the activities mentioned on the campus club website and have you done any? Mention the names : **we have various tracks in our club where people learn and contribute on their interest basis .** 

###Do you have the resources to remotely take part in activities that will be conducted?(stream,speakers etc) : **Yes**

###Does your RC know you are a part of this system? [If no then you need to inform them]: **yes**

###What activities would you like the initiative to conduct? : **QA / Webvr / Rust / Add-ons**

###Any suggestions ?We welcome and appreciate them all :

**Comment by ashwin-phadke** [comment]
Welcome to be a part of this journey @surentharan

**Comment by ashwin-phadke** [comment]
Plan along with your team accordingly!
