### ISSUE TITLE
Details of FoxCodes mozilla campus club

### ISSUE THREAD

**Issue by Ketakip** [Collaborate-Clubs/CCC-Main#2]
Hello all this is the issue template to submit the club's data so we can arrange the activities :</br>

###Club name : </br>
FoxCodes Campus Club

###Club captain name : </br>
Ketaki Phatak

###Club city : </br>
Pune

###Club email/Captain email address : </br>
ketakiphatak1997@gmail.com

###Status of the club on campus club website : </br>
Under training

###Are you aware of the activities mentioned on the campus club website and have you done any? Mention the names : </br>
We have various tracks in our club where people learn and contribute on their interest basis

###Do you have the resources to remotely take part in activities that will be conducted?(stream,speakers etc) : </br>
Yes

###Does your RC know you are a part of this system? [If no then you need to inform them]: </br>
Yes

###What activities would you like the initiative to conduct? : </br>
QA/ Webvr/ Rust/ Add-ons

###Any suggestions ?We welcome and appreciate them all : </br>

**Comment by ashwin-phadke** [comment]
Plan along with your team accordingly!
